// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXzve0XcEGYp_W0ohcnMtQez9mSuuqd0M',
    appId: '1:60393231076:web:227ba069229e1aa24292f1',
    messagingSenderId: '60393231076',
    projectId: 'diaryapp-389ed',
    authDomain: 'diaryapp-389ed.firebaseapp.com',
    databaseURL: 'https://diaryapp-389ed-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diaryapp-389ed.firebasestorage.app',
    measurementId: 'G-VP76JH9W2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB5SUWK9ajkzcY46V4MAbZi-y7nkFvAbU',
    appId: '1:60393231076:android:8b6d537dcb7287bf4292f1',
    messagingSenderId: '60393231076',
    projectId: 'diaryapp-389ed',
    databaseURL: 'https://diaryapp-389ed-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diaryapp-389ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6PlM1mgi8BkHBlkQvaHNhkULZjcrSVGE',
    appId: '1:60393231076:ios:99cb87a58ec447cf4292f1',
    messagingSenderId: '60393231076',
    projectId: 'diaryapp-389ed',
    databaseURL: 'https://diaryapp-389ed-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diaryapp-389ed.firebasestorage.app',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6PlM1mgi8BkHBlkQvaHNhkULZjcrSVGE',
    appId: '1:60393231076:ios:99cb87a58ec447cf4292f1',
    messagingSenderId: '60393231076',
    projectId: 'diaryapp-389ed',
    databaseURL: 'https://diaryapp-389ed-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diaryapp-389ed.firebasestorage.app',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXzve0XcEGYp_W0ohcnMtQez9mSuuqd0M',
    appId: '1:60393231076:web:4802c86f35b9568f4292f1',
    messagingSenderId: '60393231076',
    projectId: 'diaryapp-389ed',
    authDomain: 'diaryapp-389ed.firebaseapp.com',
    databaseURL: 'https://diaryapp-389ed-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diaryapp-389ed.firebasestorage.app',
    measurementId: 'G-M8RRMXNYPN',
  );

}